=== EloyRsua/LasPalmas-Desktop/xml/rutas.dtd
<!-- DTD para el archivo de rutas turísticas de la provincia de Las Palmas -->
<!ELEMENT rutas (ruta+)>
<!ATTLIST rutas
  xmlns:xsi CDATA #IMPLIED
  xsi:noNamespaceSchemaLocation CDATA #IMPLIED>

<!ELEMENT ruta (nombre, tipo, medio, fecha_inicio?, hora_inicio?, duracion, agencia, descripcion, personas_adecuadas, lugar_inicio, direccion_inicio, coordenadas_inicio, referencias, recomendacion, hitos, planimetria, altimetria)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT tipo (#PCDATA)>
<!ELEMENT medio (#PCDATA)>
<!ELEMENT fecha_inicio (#PCDATA)>
<!ELEMENT hora_inicio (#PCDATA)>
<!ELEMENT duracion (#PCDATA)>
<!ELEMENT agencia (#PCDATA)>
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT personas_adecuadas (#PCDATA)>
<!ELEMENT lugar_inicio (#PCDATA)>
<!ELEMENT direccion_inicio (#PCDATA)>
<!ELEMENT coordenadas_inicio (longitud, latitud, altitud)>
<!ELEMENT longitud (#PCDATA)>
<!ELEMENT latitud (#PCDATA)>
<!ELEMENT altitud (#PCDATA)>
<!ELEMENT referencias (referencia, referencia, referencia+)>
<!ELEMENT referencia (#PCDATA)>
<!ELEMENT recomendacion (#PCDATA)>
<!ELEMENT hitos (punto | hito)+>
<!ELEMENT hito (nombre, descripcion, coordenadas, distancia, fotos, videos?)>
<!ELEMENT punto (coordenadas, distancia)>
<!ELEMENT coordenadas (longitud, latitud, altitud)>
<!ELEMENT distancia (#PCDATA)>
<!ATTLIST distancia unidades CDATA #REQUIRED>
<!ELEMENT fotos (foto+)>
<!ELEMENT foto (#PCDATA)>
<!ELEMENT videos (video+)>
<!ELEMENT video (#PCDATA)>
<!ELEMENT planimetria (#PCDATA)>
<!ELEMENT altimetria (#PCDATA)>

=== EloyRsua/LasPalmas-Desktop/xml/rutas.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE rutas SYSTEM "rutas.dtd">
<rutas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="rutas.xsd">
  
  
  <ruta>
    <nombre>Ruta de la Degollada de la Goleta al Roque Nublo</nombre>
    <tipo>Senderismo</tipo>
    <medio>A pie</medio>
    <fecha_inicio>2026-05-22</fecha_inicio>
    <hora_inicio>10:00:00</hora_inicio>
    <duracion>2 horas y 30 minutos</duracion>
    <agencia>Cabildo de Gran Canaria - Medio Ambiente</agencia>
    <descripcion>Ascenso a uno de los monumentos naturales más emblemáticos de Canarias, que ofrece espectaculares vistas panorámicas de la caldera de Tejeda y el Teide.</descripcion>
    <personas_adecuadas>Personas en buena forma física y familias habituadas al senderismo.</personas_adecuadas>
    <lugar_inicio>Aparcamiento de la Degollada de la Goleta</lugar_inicio>
    <direccion_inicio>Carretera GC-600, Tejeda, Gran Canaria</direccion_inicio>
    <coordenadas_inicio>
      <longitud>-15.59776360008336</longitud>
      <latitud>27.96617844102121</latitud>
      <altitud>1600.43</altitud>
    </coordenadas_inicio>
    <referencias>
      <referencia>https://www.grancanaria.com/turismo/es/la-isla/municipios-de-gran-canaria/tejeda/roque-nublo/</referencia>
      <referencia>https://es.wikipedia.org/wiki/Roque_Nublo</referencia>
      <referencia>https://www.visor.grafcan.es/</referencia>
    </referencias>
    <recomendacion>9.5</recomendacion>
    <hitos>
      <punto>
        <coordenadas>
          <longitud>-15.59776360008336</longitud>
          <latitud>27.96617844102121</latitud>
          <altitud>1600.44</altitud>
        </coordenadas>
        <distancia unidades="metros">0.00</distancia>
      </punto>
      <punto><coordenadas>
          <longitud>-15.59777462079623</longitud>
          <latitud>27.96628020287913</latitud>
          <altitud>1600.11</altitud>
        </coordenadas>
        <distancia unidades="metros">11.37</distancia>
        </punto><punto><coordenadas>
          <longitud>-15.59781235248382</longitud>
          <latitud>27.96637544087702</latitud>
          <altitud>1598.91</altitud>
        </coordenadas>
        <distancia unidades="metros">11.22</distancia>
        </punto><punto><coordenadas>
          <longitud>-15.59795870718128</longitud>
          <latitud>27.9663697024504</latitud>
          <altitud>1592.12</altitud>
        </coordenadas>
        <distancia unidades="metros">14.39</distancia>
        </punto><punto><coordenadas>
          <longitud>-15.59804023790524</longitud>
          <latitud>27.96627074336959</latitud>
          <altitud>1590.17</altitud>
        </coordenadas>
        <distancia unidades="metros">13.61</distancia>
        </punto><punto><coordenadas>
          <longitud>-15.59813086347464</longitud>
          <latitud>27.96616476288573</latitud>
          <altitud>1588.83</altitud>
        </coordenadas>
        <distancia unidades="metros">14.77</distancia>
        </punto><punto><coordenadas>
          <longitud>-15.59856674331132</longitud>
          <latitud>27.96596445815705</latitud>
          <altitud>1583.10</altitud>
        </coordenadas>
        <distancia unidades="metros">48.26</distancia>
        </punto><punto><coordenadas>
          <longitud>-15.59888602379716</longitud>
          <latitud>27.96577161115442</latitud>
          <altitud>1583.96</altitud>
        </coordenadas>
        <distancia unidades="metros">37.99</distancia>
        </punto><punto><coordenadas>
          <longitud>-15.5993691751472</longitud>
          <latitud>27.9656231524176</latitud>
          <altitud>1580.15</altitud>
        </coordenadas>
        <distancia unidades="metros">50.24</distancia>
        </punto><punto><coordenadas>
          <longitud>-15.59972026765567</longitud>
          <latitud>27.96549207481867</latitud>
          <altitud>1575.65</altitud>
        </coordenadas>
        <distancia unidades="metros">37.43</distancia>
        </punto><punto><coordenadas>
          <longitud>-15.60014729588635</longitud>
          <latitud>27.96570302916203</latitud>
          <altitud>1572.06</altitud>
        </coordenadas>
        <distancia unidades="metros">48.05</distancia>
        </punto><punto><coordenadas>
          <longitud>-15.60019672063096</longitud>
          <latitud>27.96592676713246</latitud>
          <altitud>1565.83</altitud>
        </coordenadas>
        <distancia unidades="metros">25.35</distancia>
        </punto><punto><coordenadas>
          <longitud>-15.60036093153622</longitud>
          <latitud>27.96602697352731</latitud>
          <altitud>1564.11</altitud>
        </coordenadas>
        <distancia unidades="metros">19.60</distancia>
        </punto><punto><coordenadas>
          <longitud>-15.60043226861092</longitud>
          <latitud>27.96611928905</latitud>
          <altitud>1558.33</altitud>
        </coordenadas>
        <distancia unidades="metros">12.43</distancia>
        </punto><punto><coordenadas>
          <longitud>-15.60053208452898</longitud>
          <latitud>27.96623789847159</latitud>
          <altitud>1555.07</altitud>
        </coordenadas>
        <distancia unidades="metros">16.43</distancia>
        </punto><punto><coordenadas>
          <longitud>-15.60093742084911</longitud>
          <latitud>27.96637143694975</latitud>
          <altitud>1552.70</altitud>
        </coordenadas>
        <distancia unidades="metros">42.49</distancia>
        </punto><punto><coordenadas>
          <longitud>-15.60103593556185</longitud>
          <latitud>27.96642458402732</latitud>
          <altitud>1548.17</altitud>
        </coordenadas>
        <distancia unidades="metros">11.34</distancia>
        </punto><punto><coordenadas>
          <longitud>-15.6012846532775</longitud>
          <latitud>27.96630750632757</latitud>
          <altitud>1553.93</altitud>
        </coordenadas>
        <distancia unidades="metros">27.68</distancia>
        </punto><punto><coordenadas>
          <longitud>-15.60149357495062</longitud>
          <latitud>27.96628570327609</latitud>
          <altitud>1555.29</altitud>
        </coordenadas>
        <distancia unidades="metros">20.66</distancia>
        </punto><punto><coordenadas>
          <longitud>-15.60147492870928</longitud>
          <latitud>27.96616937106124</latitud>
          <altitud>1559.53</altitud>
        </coordenadas>
        <distancia unidades="metros">13.06</distancia>
        </punto><punto><coordenadas>
          <longitud>-15.60143604113933</longitud>
          <latitud>27.96606365900357</latitud>
          <altitud>1564.55</altitud>
        </coordenadas>
        <distancia unidades="metros">12.36</distancia>
        </punto><punto><coordenadas>
          <longitud>-15.60157917806122</longitud>
          <latitud>27.96612666497044</latitud>
          <altitud>1564.04</altitud>
        </coordenadas>
        <distancia unidades="metros">15.71</distancia>
        </punto><hito>
        <nombre>Mirador De La Goleta</nombre>
        <descripcion>Hito de interés turístico: Mirador De La Goleta.</descripcion>
        <coordenadas>
          <longitud>-15.60158731464052</longitud>
          <latitud>27.96584610257849</latitud>
          <altitud>1574.89</altitud>
        </coordenadas>
        <distancia unidades="metros">31.21</distancia>
        <fotos>
          <foto>multimedia/miradorGoleta.png</foto>
        </fotos>
      </hito>
      <punto><coordenadas>
          <longitud>-15.60178382518767</longitud>
          <latitud>27.96582887350609</latitud>
          <altitud>1576.61</altitud>
        </coordenadas>
        <distancia unidades="metros">19.39</distancia>
        </punto><hito>
        <nombre>Reloj De Sol</nombre>
        <descripcion>Hito de interés turístico: Reloj De Sol.</descripcion>
        <coordenadas>
          <longitud>-15.60216356446526</longitud>
          <latitud>27.9659506142819</latitud>
          <altitud>1579.38</altitud>
        </coordenadas>
        <distancia unidades="metros">39.68</distancia>
        <fotos>
          <foto>multimedia/relojSol.png</foto>
        </fotos>
      </hito>
      <punto><coordenadas>
          <longitud>-15.60258556321784</longitud>
          <latitud>27.96616623616898</latitud>
          <altitud>1581.84</altitud>
        </coordenadas>
        <distancia unidades="metros">47.88</distancia>
        </punto><punto><coordenadas>
          <longitud>-15.6029689431855</longitud>
          <latitud>27.96655373578121</latitud>
          <altitud>1584.23</altitud>
        </coordenadas>
        <distancia unidades="metros">57.22</distancia>
        </punto><punto><coordenadas>
          <longitud>-15.60340622077941</longitud>
          <latitud>27.96690485412501</latitud>
          <altitud>1590.84</altitud>
        </coordenadas>
        <distancia unidades="metros">58.04</distancia>
        </punto><punto><coordenadas>
          <longitud>-15.60400490178918</longitud>
          <latitud>27.96698786701954</latitud>
          <altitud>1594.53</altitud>
        </coordenadas>
        <distancia unidades="metros">59.52</distancia>
        </punto><punto><coordenadas>
          <longitud>-15.6052924669267</longitud>
          <latitud>27.96757351630565</latitud>
          <altitud>1602.31</altitud>
        </coordenadas>
        <distancia unidades="metros">142.23</distancia>
        </punto><punto><coordenadas>
          <longitud>-15.60593408897464</longitud>
          <latitud>27.96796388286946</latitud>
          <altitud>1613.90</altitud>
        </coordenadas>
        <distancia unidades="metros">76.52</distancia>
        </punto><punto><coordenadas>
          <longitud>-15.60671362640698</longitud>
          <latitud>27.96832095655471</latitud>
          <altitud>1624.75</altitud>
        </coordenadas>
        <distancia unidades="metros">86.24</distancia>
        </punto><punto><coordenadas>
          <longitud>-15.60722781456911</longitud>
